### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by tristan-gscn**
Update README to make `Win32more` easier to understand and use for newcomers

### CODE REVIEW

**Comment by ynkdir** [comment]
Could you add screenshot image to this repository and replace url with it?

**Comment by tristan-gscn** [comment]
Yes I can, I'll take care of it.

**Comment by tristan-gscn** [comment]
Normally, it's okay. Tell me if something's wrong

**Comment by ynkdir** [comment]
I would like to use a newly created image to clear copyright issues.

**Comment by tristan-gscn** [comment]
Oh sorry, I didn't understand that. I'll do it right away

**Comment by tristan-gscn** [comment]
I took a screenshot myself from my Windows 11 computer. I hope I didn't do anything wrong

**Comment by ynkdir** [comment]
Thank you.

**Pull request merged**
