### PR TITLE
Drop `Windows.all`

### PR DESCRIPTION
**Pull request by byehack**

### CODE REVIEW

**Comment by ynkdir** [comment]
Thank you for your pull request.

Currently, all.py loads modules lazily.  For example

```python
import Windows.all
Windows.all.MessageBoxW(...)  # <- only WindowsAndMessaging and its dependencies are loaded.
```

But with this changes, `import Windows.all` causes loading all modules.

Do you prefer loading all modules at once?

It doesn't matter to me.

**Comment by byehack** [comment]
> Currently, all.py loads modules lazily.

True, and consider gc will remove imported modules from memory after getting method names.


> Do you prefer loading all modules at once?

I don't use `Windows.all` at all, bcz for each method I first search in [here](https://microsoft.github.io/windows-docs-rs/doc/windows/index.html) then directly import it.
I prefer to have lower size final product.

Or instead of this PR, maybe we can remove `Windows.all` like other [libraries](https://github.com/microsoft/win32metadata/blob/main/docs/projections.md#consuming-language-projections)?

**Comment by ynkdir** [comment]
I guess it is better to remove Windows.all.

win32more is my personal experimental project.  I am waiting official projection.

**Comment by byehack** [comment]
> I am waiting official projection.



I think there is not any plan for implement metadata translator to python from Microsoft, at least it won't happened in near future.

So, I'll try few commits to drop `Windows.all`.

**Comment by byehack** [comment]
Only tests imports header remained.

**Comment by byehack** [comment]
Do you also agree that to remove `Windows` folder from repo or just I think?
You can specify in `setup.py` to build this folder on install package. by this, download package size would drops would be much lower.

**Comment by ynkdir** [comment]
No problem.

**Comment by byehack** [comment]
- [ ] Update tests import headers
- [ ] Update setup.py

**Comment by byehack** [comment]
I tested with py3.11 and win11 and I think it's ready now, you can merge this PR after you updated the tests files (or maybe in another time?).

**Comment by ynkdir** [comment]
Thank you.  I will update tests.

**Comment by ynkdir** [comment]
I have re-added generated files to keep build process and config file simple.

**Pull request merged**
